# ─────────────────────────────────────────────
# Face Mask Detection — Docker Compose
# Role 7: Deployer — Gehad
# ─────────────────────────────────────────────

version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../model:/app/model
    networks:
      - mask-network

  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    networks:
      - mask-network

networks:
  mask-network:
    driver: bridge